version: '3.7'

services:
  tsm:
    container_name: tsm
    image: alkiviadroot/taekwondo-student-manager:latest
    restart: unless-stopped
    ports:
      - '8090:8090'
      - '3000:3000'
    volumes:
      - ./pocketbase:/pb_data
    env_file:
      - ./.env

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    env_file:
      - ./.env
